### ISSUE TITLE
AllSubs Error when searching

### ISSUE THREAD

**Issue by mich3lam** [KodiBeginner/addons#1]
So I have encountered this issue on multiple devices, some things work, others don't. When trying to search for subtitles it says it encountered some error and I should check the log file. Any chance for a fix?

Thank you!

```
2020-01-17 20:12:51.605 T:16504   ERROR: WARNING:root:['heb', 'eng']
2020-01-17 20:12:51.606 T:16504   ERROR: WARNING:root:[{'imdbid': '3315342', 'sublanguageid': 'heb,eng'}, {'query': 'tt3315342', 'sublanguageid': 'heb,eng', 'year': '2017'}]
2020-01-17 20:12:51.643 T:19032 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-01-17 20:12:52.077 T:23120   ERROR: WARNING:root:['\r\n<li>\r\n\t<div class="title">\r\n\t\t<a href="/subtitles/logan">Logan (2010)</a>\r\n\t</div>\r\n\t<div class="subtle count">\r\n\r\n\t\t2 subtitles\r\n\t</div>\r\n\r\n</li>\r\n<li>\r\n\t<div class="title">\r\n\t\t<a href="/subtitles/logan-2017">Logan (2017)</a>\r\n\t</div>\r\n\t<div class="subtle count">\r\n\r\n\t\t287 subtitles\r\n\t</div>\r\n\r\n</li>\r\n\t\t\t\t']
2020-01-17 20:12:52.144 T:19032 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-01-17 20:12:53.444 T:2552 WARNING: Previous line repeats 2 times.
2020-01-17 20:12:53.444 T:2552   ERROR: WARNING:root:sc_subtitle
2020-01-17 20:12:53.490 T:2552   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode characters in position 4-5: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\micam\AppData\Roaming\Kodi\addons\service.subtitles.All_Subs\autosub.py", line 68, in <module>
                                                search_all(3,(all_setting))
                                              File "C:\Users\micam\AppData\Roaming\Kodi\addons\service.subtitles.All_Subs\service.py", line 2341, in search_all
                                                array_subs=[str(x).lower() for x in array_subs if x != '']
                                            UnicodeEncodeError: 'ascii' codec can't encode characters in position 4-5: ordinal not in range(128)
                                            -->End of Python script error report<--
```

**Comment by megarepo** [comment]
Fixed in version 2.1.2
Please check with the new version.

**Comment by mich3lam** [comment]
Sadly, it did not fix it. Still gives an error when searching subtitles for Logan for example :(
